const productos = [
    {
        id: 1,
        categoria: "remeras",
        nombreProducto: "Remera Python",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-1.jpeg",
    },
    {
        id: 2,
        categoria: "remeras",
        nombreProducto: "Remera ...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-2.jpeg",
    },
    {
        id: 3,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-3.jpeg",
    },
    {
        id: 4,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-4.jpeg",
    },
    {
        id: 5,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-5.jpeg",
    },
    {
        id: 6,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-6.jpeg",
    },
    {
        id: 7,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-7.jpeg",
    },
    {
        id: 8,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-8.jpeg",
    },
    {
        id: 9,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-9.jpeg",
    },
    {
        id: 10,
        categoria: "remeras",
        nombreProducto: "Remera...",
        precio: 3000,
        cantidad: 1,
        img: "../multimedia/categoria-remeras/producto-remera-10.jpeg",
    },

];
