const productos = [
    {
        id: 1,
        categoria: "remeras",
        nombreProducto: "Remera Error 404",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-1.jpeg",
    },
    {
        id: 2,
        categoria: "remeras",
        nombreProducto: "Remera Git-Hub",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-2.jpeg",
    },
    {
        id: 3,
        categoria: "remeras",
        nombreProducto: "Remera JavaScript",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-3.jpeg",
    },
    {
        id: 4,
        categoria: "remeras",
        nombreProducto: "Remera Python",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-4.jpeg",
    },
    {
        id: 5,
        categoria: "remeras",
        nombreProducto: "Remera Python",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-5.jpeg",
    },
    {
        id: 6,
        categoria: "remeras",
        nombreProducto: "Remera Ctrl",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-6.jpeg",
    },
    {
        id: 7,
        categoria: "remeras",
        nombreProducto: "Remera Money",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-7.jpeg",
    },
    {
        id: 8,
        categoria: "remeras",
        nombreProducto: "Remera GAME",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-8.jpeg",
    },
    {
        id: 9,
        categoria: "remeras",
        nombreProducto: "Remera JS",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-9.jpeg",
    },
    {
        id: 10,
        categoria: "remeras",
        nombreProducto: "Remera Ctrl+Z",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-remera-10.jpeg",
    },
    {
        id: 11,
        categoria: "comics",
        nombreProducto: "X-men La gente de Mañana",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-20.jpeg",
    },
    {
        id: 12,
        categoria: "comics",
        nombreProducto: "The Ultimate - Vengadores",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-21.jpeg",
    },
    {
        id: 13,
        categoria: "comics",
        nombreProducto: "La Muerte de Wolverine",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-22.jpeg",
    },
    {
        id: 14,
        categoria: "comics",
        nombreProducto: "Spiderman - Un Mundo compartido",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-23.jpeg",
    },
    {
        id: 15,
        categoria: "comics",
        nombreProducto: "Superman & Wonder Woman",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-24.jpeg",
    },
    {
        id: 16,
        categoria: "comics",
        nombreProducto: "Liga de la justicia - Escalera al Cielo",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-25.jpeg",
    },
    {
        id: 17,
        categoria: "comics",
        nombreProducto: "Las Aventuras de Batman",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-26.jpeg",
    },
    {
        id: 18,
        categoria: "comics",
        nombreProducto: "Sand Man - de Neil Gaiman",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-27.jpeg",
    },
    {
        id: 19,
        categoria: "comics",
        nombreProducto: "Batman . La Borma Asesina",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-28.jpeg",
    },
    {
        id: 20,
        categoria: "comics",
        nombreProducto: "HellBlazer - Habitos Peligrosos",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-29.jpeg",
    },
    {
        id: 21,
        categoria: "comics",
        nombreProducto: "Batman - Knightfall",
        precio: 3000,
        cantidad: 1,
        img: "./media/productos-imagenes/producto-comic-30.jpeg",
    },
    
];
